# Generated by Django 4.0.2 on 2022-02-21 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='life_question',
            name='q_hit',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='life_question',
            name='voter',
            field=models.ManyToManyField(related_name='voter_life_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
