# Generated by Django 4.0.2 on 2022-02-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainBoard', '0002_life_question_q_hit_life_question_voter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
