# Generated by Django 4.0.2 on 2022-02-21 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainBoard', '0004_life_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='life_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('life_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainBoard.life_question')),
            ],
        ),
    ]
