# Generated by Django 4.0.2 on 2022-02-21 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreeBoard', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='t_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='t_question',
            new_name='question',
        ),
    ]
