# Generated by Django 4.0.2 on 2022-02-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stopword',
            fields=[
                ('word_seq', models.AutoField(primary_key=True, serialize=False)),
                ('word_content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'logosboard_stopword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('syn_seq', models.AutoField(primary_key=True, serialize=False)),
                ('syn_content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'logosboard_synonym',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_type', models.IntegerField(blank=True, null=True)),
                ('lawc_name', models.TextField(blank=True, db_column='lawC_name', null=True)),
                ('law_content', models.TextField(blank=True, null=True)),
                ('m_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_law',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TLog',
            fields=[
                ('log_seq', models.AutoField(primary_key=True, serialize=False)),
                ('log_key', models.CharField(max_length=200)),
                ('log_full', models.TextField()),
                ('log_time', models.DateTimeField()),
                ('log_status', models.CharField(max_length=1)),
                ('id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 't_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAd',
            fields=[
                ('ad_seq', models.AutoField(primary_key=True, serialize=False)),
                ('ad_prenum', models.CharField(max_length=200)),
                ('ad_content', models.TextField()),
                ('ad_subj', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_ad',
            },
        ),
        migrations.CreateModel(
            name='TCivil',
            fields=[
                ('civ_seq', models.AutoField(primary_key=True, serialize=False)),
                ('civ_prenum', models.CharField(max_length=200)),
                ('civ_content', models.TextField()),
                ('civ_subj', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_civil',
            },
        ),
        migrations.CreateModel(
            name='TCriminal',
            fields=[
                ('cri_seq', models.AutoField(primary_key=True, serialize=False)),
                ('cri_prenum', models.CharField(max_length=200)),
                ('cri_content', models.TextField()),
                ('cri_subj', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_criminal',
            },
        ),
        migrations.CreateModel(
            name='TFamily',
            fields=[
                ('fam_seq', models.AutoField(primary_key=True, serialize=False)),
                ('fam_prenum', models.CharField(blank=True, max_length=200, null=True)),
                ('fam_subj', models.CharField(blank=True, max_length=200, null=True)),
                ('fam_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_family',
            },
        ),
        migrations.CreateModel(
            name='TCriminalSummary',
            fields=[
                ('cri_seq', models.OneToOneField(db_column='cri_seq', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='LogosBoard.tcriminal')),
                ('cri_subj', models.CharField(max_length=200)),
                ('cri_sum_content', models.TextField()),
                ('cri_sum_keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('cri_sum_abst', models.TextField()),
                ('ref_law', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_criminal_summary',
            },
        ),
    ]
